/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jireh Castillo
 */
public class ViewCifrado extends javax.swing.JFrame {

    /**
     * Creates new form ViewCifrado
     */
    public ViewCifrado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_areas = new javax.swing.JTextArea();
        jL_titulo = new javax.swing.JLabel();
        jMB_menu_archivo = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMI_abrir = new javax.swing.JMenuItem();
        jMI_cifrar = new javax.swing.JMenuItem();
        jMI_descifrar = new javax.swing.JMenuItem();
        jMI_guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));

        jTA_areas.setBackground(new java.awt.Color(204, 102, 255));
        jTA_areas.setColumns(20);
        jTA_areas.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTA_areas.setRows(5);
        jScrollPane1.setViewportView(jTA_areas);

        jL_titulo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jL_titulo.setForeground(new java.awt.Color(0, 204, 0));
        jL_titulo.setText("Bloc de Notas con Cifrado César ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jL_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jL_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMB_menu_archivo.setBackground(new java.awt.Color(204, 102, 255));

        jMenu2.setForeground(new java.awt.Color(0, 153, 0));
        jMenu2.setText("Editar");
        jMB_menu_archivo.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(204, 153, 255));
        jMenu1.setForeground(new java.awt.Color(0, 153, 0));
        jMenu1.setText("Archivo");

        jMI_abrir.setText("Abrir");
        jMenu1.add(jMI_abrir);

        jMI_cifrar.setBackground(new java.awt.Color(204, 102, 255));
        jMI_cifrar.setText("Cifrar");
        jMI_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_cifrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_cifrar);

        jMI_descifrar.setBackground(new java.awt.Color(204, 51, 255));
        jMI_descifrar.setText("Descifrar");
        jMenu1.add(jMI_descifrar);

        jMI_guardar.setBackground(new java.awt.Color(204, 0, 255));
        jMI_guardar.setText("Guardar");
        jMenu1.add(jMI_guardar);

        jMB_menu_archivo.add(jMenu1);

        setJMenuBar(jMB_menu_archivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMI_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_cifrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMI_cifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCifrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_titulo;
    public javax.swing.JMenuBar jMB_menu_archivo;
    public javax.swing.JMenuItem jMI_abrir;
    public javax.swing.JMenuItem jMI_cifrar;
    public javax.swing.JMenuItem jMI_descifrar;
    public javax.swing.JMenuItem jMI_guardar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTA_areas;
    // End of variables declaration//GEN-END:variables
}
